import type { IRenovatePr, ISettings } from '../types';
import { DEFAULT_RENOVATE_AUTHORS, DEPENDABOT_AUTHOR } from '../types';

export type BotKind = 'dependabot' | 'renovate';

/**
 * A hint that a pull request came from Renovate, short of its author saying so.
 */
export type RenovateSignal = 'branch' | 'footer' | 'label';

const RENOVATE_FOOTER = 'this pr has been generated by renovate bot';

/**
 * Decides which bot opened a pull request, by author login alone.
 *
 * Author matching is the whole test on purpose. The secondary signals in {@link renovateSignals}
 * are suggestive rather than conclusive — a human can open a branch called `renovate/something`,
 * and acting on a label would put their pull request in the merge queue.
 * @param pr A pull request.
 * @param settings The current settings, which may add logins and may admit Dependabot.
 */
export function identifyBot(pr: IRenovatePr, settings: ISettings): BotKind | undefined {
  const author = pr.author.toLowerCase();
  const renovateAuthors = [ ...DEFAULT_RENOVATE_AUTHORS, ...settings.extraAuthors ]
    .map(login => login.toLowerCase());
  if (renovateAuthors.includes(author)) {
    return 'renovate';
  }
  if (settings.includeDependabot && author === DEPENDABOT_AUTHOR.toLowerCase()) {
    return 'dependabot';
  }
  return undefined;
}

/**
 * Lists the secondary signals a pull request carries.
 *
 * These are what identifies a self-hosted Renovate running under a login nobody has configured
 * yet. They are shown rather than acted on, so the fix is always to add the login in the settings.
 * @param pr A pull request.
 * @param body Its body, when one has been loaded.
 */
export function renovateSignals(pr: IRenovatePr, body?: string): RenovateSignal[] {
  const signals: RenovateSignal[] = [];
  if (/(?:^|\/)renovate\//u.test(pr.branch)) {
    signals.push('branch');
  }
  if (pr.labels.some(label => label.toLowerCase() === 'dependencies')) {
    signals.push('label');
  }
  if (body !== undefined && body.toLowerCase().includes(RENOVATE_FOOTER)) {
    signals.push('footer');
  }
  return signals;
}
