import { describe, expect, it } from 'vitest';
import { identifyBot, renovateSignals } from '../../src/lib/renovate/identify';
import { SETTINGS, pr } from '../fixtures';

describe('identifyBot', () => {
  it('recognises the hosted Mend app', () => {
    expect(identifyBot(pr({ author: 'renovate[bot]' }), SETTINGS)).toBe('renovate');
  });

  it('recognises the usual self-hosted service accounts', () => {
    expect(identifyBot(pr({ author: 'renovate-bot' }), SETTINGS)).toBe('renovate');
    expect(identifyBot(pr({ author: 'renovate' }), SETTINGS)).toBe('renovate');
  });

  it('ignores the casing of a login', () => {
    expect(identifyBot(pr({ author: 'Renovate[bot]' }), SETTINGS)).toBe('renovate');
  });

  it('recognises an extra login the user configured', () => {
    expect(identifyBot(pr({ author: 'our-bot' }), SETTINGS)).toBeUndefined();
    expect(identifyBot(pr({ author: 'our-bot' }), { ...SETTINGS, extraAuthors: [ 'our-bot' ]}))
      .toBe('renovate');
  });

  it('keeps Dependabot behind its own setting', () => {
    expect(identifyBot(pr({ author: 'dependabot[bot]' }), SETTINGS)).toBeUndefined();
    expect(identifyBot(pr({ author: 'dependabot[bot]' }), { ...SETTINGS, includeDependabot: true }))
      .toBe('dependabot');
  });

  it('matches on the author alone, not on the secondary signals', () => {
    const looksRight = pr({ author: 'a-human', branch: 'renovate/lodash-4.x', labels: [ 'dependencies' ]});
    expect(identifyBot(looksRight, SETTINGS)).toBeUndefined();
  });
});

describe('renovateSignals', () => {
  it('reports nothing for an ordinary pull request', () => {
    expect(renovateSignals(pr({ branch: 'feature/x', labels: []}))).toEqual([]);
  });

  it('reports a Renovate branch prefix', () => {
    expect(renovateSignals(pr({ branch: 'renovate/lodash-4.x', labels: []}))).toEqual([ 'branch' ]);
  });

  it('reports the dependencies label', () => {
    expect(renovateSignals(pr({ branch: 'x', labels: [ 'Dependencies' ]}))).toEqual([ 'label' ]);
  });

  it('reports the generated-by footer, when a body has been loaded', () => {
    expect(renovateSignals(pr({ branch: 'x', labels: []}), 'This PR has been generated by Renovate Bot.'))
      .toEqual([ 'footer' ]);
  });

  it('reports every signal it finds, so the inspector can show them', () => {
    expect(renovateSignals(
      pr({ branch: 'renovate/x', labels: [ 'dependencies' ]}),
      'This PR has been generated by Renovate Bot.',
    )).toEqual([ 'branch', 'label', 'footer' ]);
  });
});
